export const singleCertFieldConfigs = {
  free: {
    fields: [
      {
        key: "CertificateNo",
        label: "Certificate Number",
        name: "CertificateNo",
        placeholder: "Certificate Number",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "recipientEmail",
        label: "Email ID",
        name: "recipientEmail",
        placeholder: "Email ID",
        inputType: "email",
        fieldType: "Inputs",
      },
      {
        key: "Titels",
        label: "Title",
        name: "Titels",
        options: "optionsForTitle",
        fieldType: "TitleSelect",
      },
      {
        key: "StudentName",
        label: "Name of The Student",
        name: "StudentName",
        placeholder: "Name of The Student",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "Duration",
        label: "Course Duration",
        name: "Duration",
        placeholder: "Course Duration",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "Course",
        label: "Name Of The Course",
        name: "Course",
        placeholder: "Name Of The Course",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "Date",
        label: "Completion Date",
        name: "Date",
        placeholder: "Completion Date",
        inputType: "date",
        fieldType: "Inputs",
      },
    ],
  },

  asdc: {
    fields: [
      {
        key: "CertificateNo",
        label: "Certificate Number",
        name: "CertificateNo",
        placeholder: "Certificate Number",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "recipientEmail",
        label: "Email ID",
        name: "recipientEmail",
        placeholder: "Email ID",
        inputType: "email",
        fieldType: "Inputs",
      },
      {
        key: "Titels",
        label: "Title",
        name: "Titels",
        options: "optionsForTitle",
        fieldType: "TitleSelect",
      },
      {
        key: "StudentName",
        label: "Name of The Student",
        name: "StudentName",
        placeholder: "Name of The Student",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "Duration",
        label: "Course Duration",
        name: "Duration",
        placeholder: "Course Duration",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "Course",
        label: "Name Of The Course",
        name: "Course",
        placeholder: "Name Of The Course",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "Date",
        label: "Completion Date",
        name: "Date",
        placeholder: "Completion Date",
        inputType: "date",
        fieldType: "Inputs",
      },
    ],
  },

  college: {
    fields: [
      {
        key: "CertificateNo",
        label: "Certificate Number",
        name: "CertificateNo",
        placeholder: "Certificate Number",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "recipientEmail",
        label: "Email ID",
        name: "recipientEmail",
        placeholder: "Email ID",
        inputType: "email",
        fieldType: "Inputs",
      },
      {
        key: "Titels",
        label: "Title",
        name: "Titels",
        options: "optionsForTitle",
        fieldType: "TitleSelect",
      },
      {
        key: "StudentName",
        label: "Name of The Student",
        name: "StudentName",
        placeholder: "Name of The Student",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "Duration",
        label: "Department Name",
        name: "Duration",
        placeholder: "Department Name",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "Course",
        label: "Name Of The Course",
        name: "Course",
        placeholder: "Name Of The Course",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "CollegeName",
        label: "College Name",
        name: "CollegeName",
        placeholder: "College Name",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "StartDate",
        label: "Start Date",
        name: "StartDate",
        placeholder: "Start Date",
        inputType: "date",
        fieldType: "Inputs",
      },
      {
        key: "EndDate",
        label: "End Date",
        name: "EndDate",
        placeholder: "End Date",
        inputType: "date",
        fieldType: "Inputs",
      },
      {
        key: "CollegeImage",
        label: "College Image",
        name: "CollegeImage",
        fieldType: "ImageUpload",
        accept: "image/*",
      },
      {
        key: "Signature1",
        label: "First Signature",
        name: "Signature1",
        fieldType: "ImageUpload",
        accept: "image/*",
      },
      {
        key: "Mng_Designation1",
        label: "First Mng Designation",
        name: "Mng_Designation1",
        placeholder: "First Mng Designation",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "Mng_Desg_Add1",
        label: "First Mng Address",
        name: "Mng_Desg_Add1",
        placeholder: "First Mng Address",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "Signature2",
        label: "Second Signature",
        name: "Signature2",
        fieldType: "ImageUpload",
        accept: "image/*",
      },
      {
        key: "Mng_Designation2",
        label: "Second Mng Designation",
        name: "Mng_Designation2",
        placeholder: "Second Mng Designation",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "Mng_Desg_Add2",
        label: "Second Mng Address",
        name: "Mng_Desg_Add2",
        placeholder: "Second Mng Address",
        inputType: "text",
        fieldType: "Inputs",
      },
    ],
  },

  paid: {
    fields: [
      {
        key: "CertificateNo",
        label: "Certificate Number",
        name: "CertificateNo",
        placeholder: "Certificate Number",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "recipientEmail",
        label: "Email ID",
        name: "recipientEmail",
        placeholder: "Email ID",
        inputType: "email",
        fieldType: "Inputs",
      },
      {
        key: "Titels",
        label: "Title",
        name: "Titels",
        options: "optionsForTitle",
        fieldType: "TitleSelect",
      },
      {
        key: "StudentName",
        label: "Name of The Student",
        name: "StudentName",
        placeholder: "Name of The Student",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "Duration",
        label: "Course Duration",
        name: "Duration",
        placeholder: "Course Duration",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "Course",
        label: "Name Of The Course",
        name: "Course",
        placeholder: "Name Of The Course",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "Date",
        label: "Completion Date",
        name: "Date",
        placeholder: "Completion Date",
        inputType: "date",
        fieldType: "Inputs",
      },
    ],
  },

  shortterm: {
    fields: [
      {
        key: "CertificateNo",
        label: "Certificate Number",
        name: "CertificateNo",
        placeholder: "Certificate Number",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "recipientEmail",
        label: "Email ID",
        name: "recipientEmail",
        placeholder: "Email ID",
        inputType: "email",
        fieldType: "Inputs",
      },
      {
        key: "Titels",
        label: "Title",
        name: "Titels",
        options: "optionsForTitle",
        fieldType: "TitleSelect",
      },
      {
        key: "StudentName",
        label: "Name of The Student",
        name: "StudentName",
        placeholder: "Name of The Student",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "Duration",
        label: "Course Duration",
        name: "Duration",
        placeholder: "Course Duration",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "Course",
        label: "Name Of The Course",
        name: "Course",
        placeholder: "Name Of The Course",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "StartDate",
        label: "Start Date",
        name: "StartDate",
        placeholder: "Start Date",
        inputType: "date",
        fieldType: "Inputs",
      },
      {
        key: "EndDate",
        label: "End Date",
        name: "EndDate",
        placeholder: "End Date",
        inputType: "date",
        fieldType: "Inputs",
      },
    ],
  },

  pgp: {
    fields: [
      {
        key: "CertificateNo",
        label: "Certificate Number",
        name: "CertificateNo",
        placeholder: "Certificate Number",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "RegNo",
        label: "Registration Number",
        name: "RegNo",
        placeholder: "Registration Number",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "recipientEmail",
        label: "Email ID",
        name: "recipientEmail",
        placeholder: "Email ID",
        inputType: "email",
        fieldType: "Inputs",
      },
      {
        key: "Titels",
        label: "Title",
        name: "Titels",
        options: "optionsForTitle",
        fieldType: "TitleSelect",
      },
      {
        key: "StudentName",
        label: "Name of The Student",
        name: "StudentName",
        placeholder: "Name of The Student",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "Duration",
        label: "Course Duration",
        name: "Duration",
        placeholder: "Course Duration",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "Course",
        label: "Name Of The Course",
        name: "Course",
        placeholder: "Name Of The Course",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "Date",
        label: "Completion Date",
        name: "Date",
        placeholder: "Completion Date",
        inputType: "date",
        fieldType: "Inputs",
      },
    ],
  },

  lor: {
    fields: [
      {
        key: "CertificateNo",
        label: "Certificate Number",
        name: "CertificateNo",
        placeholder: "Certificate Number",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "recipientEmail",
        label: "Email ID",
        name: "recipientEmail",
        placeholder: "Email ID",
        inputType: "email",
        fieldType: "Inputs",
      },
      {
        key: "Titels",
        label: "Title",
        name: "Titels",
        options: "optionsForTitle",
        fieldType: "TitleSelect",
      },
      {
        key: "StudentName",
        label: "Name of The Student",
        name: "StudentName",
        placeholder: "Name of The Student",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "Course",
        label: "Name Of The Course",
        name: "Course",
        placeholder: "Name Of The Course",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "Date",
        label: "Completion Date",
        name: "Date",
        placeholder: "Completion Date",
        inputType: "date",
        fieldType: "Inputs",
      },
      {
        key: "Signature1",
        label: "First Signature",
        name: "Signature1",
        fieldType: "ImageUpload",
        accept: "image/*",
      },
    ],
  },

  internship: {
    fields: [
      {
        key: "recipientEmail",
        label: "Email ID",
        name: "recipientEmail",
        placeholder: "Email ID",
        inputType: "email",
        fieldType: "Inputs",
      },
      {
        key: "Titels",
        label: "Title",
        name: "Titels",
        options: "optionsForTitle",
        fieldType: "TitleSelect",
      },
      {
        key: "StudentName",
        label: "Name of The Student",
        name: "StudentName",
        placeholder: "Name of The Student",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "CollegeName",
        label: "College Name",
        name: "CollegeName",
        placeholder: "College Name",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "Course",
        label: "Name Of The Course",
        name: "Course",
        placeholder: "Name Of The Course",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "Duration",
        label: "Course Duration",
        name: "Duration",
        placeholder: "Course Duration",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "Date",
        label: "Completion Date",
        name: "Date",
        placeholder: "Completion Date",
        inputType: "date",
        fieldType: "Inputs",
      },
      {
        key: "Signature1",
        label: "First Signature",
        name: "Signature1",
        fieldType: "ImageUpload",
        accept: "image/*",
      },
    ],
  },

  bonafied: {
    fields: [
      {
        key: "CertificateNo",
        label: "Certificate Number",
        name: "CertificateNo",
        placeholder: "Certificate Number",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "recipientEmail",
        label: "Email ID",
        name: "recipientEmail",
        placeholder: "Email ID",
        inputType: "email",
        fieldType: "Inputs",
      },
      {
        key: "Titels",
        label: "Title",
        name: "Titels",
        options: "optionsForTitle",
        fieldType: "TitleSelect",
      },
      {
        key: "StudentName",
        label: "Name of The Student",
        name: "StudentName",
        placeholder: "Name of The Student",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "Course",
        label: "Name Of The Course",
        name: "Course",
        placeholder: "Name Of The Course",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "CoursePrice",
        label: "Course Price",
        name: "CoursePrice",
        placeholder: "Course Price",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "Duration",
        label: "Course Duration",
        name: "Duration",
        placeholder: "Course Duration",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "CollegeName",
        label: "College Name",
        name: "CollegeName",
        placeholder: "College Name",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "Date",
        label: "Completion Date",
        name: "Date",
        placeholder: "Completion Date",
        inputType: "date",
        fieldType: "Inputs",
      },
      {
        key: "Signature1",
        label: "First Signature",
        name: "Signature1",
        fieldType: "ImageUpload",
        accept: "image/*",
      },
    ],
  },

  clearance: {
    fields: [
      {
        key: "recipientEmail",
        label: "Email ID",
        name: "recipientEmail",
        placeholder: "Email ID",
        inputType: "email",
        fieldType: "Inputs",
      },
      {
        key: "StudentName",
        label: "Name of The Student",
        name: "StudentName",
        placeholder: "Name of The Student",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "Course",
        label: "Name Of The Course",
        name: "Course",
        placeholder: "Name Of The Course",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "Mode",
        label: "Mode Of Payment",
        name: "Mode",
        placeholder: "Mode Of Payment",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "CoursePrice",
        label: "Course Price",
        name: "CoursePrice",
        placeholder: "Course Price",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "Collected_Amount",
        label: "Collected Amount",
        name: "Collected_Amount",
        placeholder: "Collected Amount",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "Outstanding_dues",
        label: "Outstanding Dues",
        name: "Outstanding_dues",
        placeholder: "Outstanding Dues",
        inputType: "text",
        fieldType: "Inputs",
      },
    ],
  },

  facultyone: {
    fields: [
      {
        key: "CertificateNo",
        label: "Certificate Number",
        name: "CertificateNo",
        placeholder: "Certificate Number",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "recipientEmail",
        label: "Email ID",
        name: "recipientEmail",
        placeholder: "Email ID",
        inputType: "email",
        fieldType: "Inputs",
      },
      {
        key: "Titels",
        label: "Title",
        name: "Titels",
        options: "optionsForTitle",
        fieldType: "TitleSelect",
      },
      {
        key: "Student_Designation",
        label: "Student Designation",
        name: "Student_Designation",
        placeholder: "Designation",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "StudentName",
        label: "Name of The Student",
        name: "StudentName",
        placeholder: "Name of The Student",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "CollegeName",
        label: "College Name",
        name: "CollegeName",
        placeholder: "College Name",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "Course",
        label: "Name Of The Course",
        name: "Course",
        placeholder: "Name Of The Course",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "StartDate",
        label: "Start Date",
        name: "StartDate",
        placeholder: "Start Date",
        inputType: "date",
        fieldType: "Inputs",
      },
      {
        key: "EndDate",
        label: "End Date",
        name: "EndDate",
        placeholder: "End Date",
        inputType: "date",
        fieldType: "Inputs",
      },
      {
        key: "CollegeImage",
        label: "College Image",
        name: "CollegeImage",
        fieldType: "ImageUpload",
        accept: "image/*",
      },
      {
        key: "Signature1",
        label: "First Signature",
        name: "Signature1",
        fieldType: "ImageUpload",
        accept: "image/*",
      },
      {
        key: "Mng_Designation1",
        label: "First Mng Designation",
        name: "Mng_Designation1",
        placeholder: "First Mng Designation",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "Mng_Desg_Add1",
        label: "First Mng Address",
        name: "Mng_Desg_Add1",
        placeholder: "First Mng Address",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "Signature2",
        label: "Second Signature",
        name: "Signature2",
        fieldType: "ImageUpload",
        accept: "image/*",
      },
      {
        key: "Mng_Designation2",
        label: "Second Mng Designation",
        name: "Mng_Designation2",
        placeholder: "Second Mng Designation",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "Mng_Desg_Add2",
        label: "Second Mng Address",
        name: "Mng_Desg_Add2",
        placeholder: "Second Mng Address",
        inputType: "text",
        fieldType: "Inputs",
      },
    ],
  },

  facultytwo: {
    fields: [
      {
        key: "CertificateNo",
        label: "Certificate Number",
        name: "CertificateNo",
        placeholder: "Certificate Number",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "recipientEmail",
        label: "Email ID",
        name: "recipientEmail",
        placeholder: "Email ID",
        inputType: "email",
        fieldType: "Inputs",
      },
      {
        key: "Titels",
        label: "Title",
        name: "Titels",
        options: "optionsForTitle",
        fieldType: "TitleSelect",
      },
      {
        key: "Student_Designation",
        label: "Student Designation",
        name: "Student_Designation",
        placeholder: "Designation",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "StudentName",
        label: "Name of The Student",
        name: "StudentName",
        placeholder: "Name of The Student",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "CollegeName",
        label: "College Name",
        name: "CollegeName",
        placeholder: "College Name",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "Course",
        label: "Name Of The Course",
        name: "Course",
        placeholder: "Name Of The Course",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "StartDate",
        label: "Start Date",
        name: "StartDate",
        placeholder: "Start Date",
        inputType: "date",
        fieldType: "Inputs",
      },
      {
        key: "EndDate",
        label: "End Date",
        name: "EndDate",
        placeholder: "End Date",
        inputType: "date",
        fieldType: "Inputs",
      },
      {
        key: "CollegeImage",
        label: "College Image",
        name: "CollegeImage",
        fieldType: "ImageUpload",
        accept: "image/*",
      },
      {
        key: "Signature1",
        label: "First Signature",
        name: "Signature1",
        fieldType: "ImageUpload",
        accept: "image/*",
      },
      {
        key: "Mng_Designation1",
        label: "First Mng Designation",
        name: "Mng_Designation1",
        placeholder: "First Mng Designation",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "Mng_Desg_Add1",
        label: "First Mng Address",
        name: "Mng_Desg_Add1",
        placeholder: "First Mng Address",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "Signature2",
        label: "Second Signature",
        name: "Signature2",
        fieldType: "ImageUpload",
        accept: "image/*",
      },
      {
        key: "Mng_Designation2",
        label: "Second Mng Designation",
        name: "Mng_Designation2",
        placeholder: "Second Mng Designation",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "Mng_Desg_Add2",
        label: "Second Mng Address",
        name: "Mng_Desg_Add2",
        placeholder: "Second Mng Address",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "Signature3",
        label: "Third Signature",
        name: "Signature3",
        fieldType: "ImageUpload",
        accept: "image/*",
      },
      {
        key: "Mng_Designation3",
        label: "Third Mng Designation",
        name: "Mng_Designation3",
        placeholder: "Third Mng Designation",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "Mng_Desg_Add3",
        label: "Third Mng Address",
        name: "Mng_Desg_Add3",
        placeholder: "Third Mng Address",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "Signature4",
        label: "Fourth Signature",
        name: "Signature4",
        fieldType: "ImageUpload",
        accept: "image/*",
      },
      {
        key: "Mng_Designation4",
        label: "Fourth Mng Designation",
        name: "Mng_Designation4",
        placeholder: "Fourth Mng Designation",
        inputType: "text",
        fieldType: "Inputs",
      },
      {
        key: "Mng_Desg_Add4",
        label: "Fourth Mng Address",
        name: "Mng_Desg_Add4",
        placeholder: "Fourth Mng Address",
        inputType: "text",
        fieldType: "Inputs",
      },
    ],
  },
};

export const bulkCertFieldConfigs = {
  free: {
    fields: [
      {
        key: "xlsx",
        label: "Add xlsx sheet here",
        name: "ExcelSheet",
        fieldType: "FileUpload",
        accept: ".xlsx, .xls, .numbers",
      },
    ],
    xlsxdata: [
      {
        recipientEmail: "kbs.li2n@gmail.com",
        CertificateNo: "SSA-01-2406897657",
        Titels: "Mr / Mrs/ Miss",
        StudentName: "Kumar Biplab",
        Duration: "2 months",
        Course: "MERN Stack",
        Date: "10th June 2024",
      },
    ],
    fileName: "Free_Course.xlsx",
  },

  asdc: {
    fields: [
      {
        key: "xlsx",
        label: "Add xlsx sheet here",
        name: "ExcelSheet",
        fieldType: "FileUpload",
        accept: ".xlsx, .xls, .numbers",
      },
    ],
    xlsxdata: [
      {
        recipientEmail: "kbs.li2n@gmail.com",
        CertificateNo: "SSA-01-2406897657",
        Titels: "Mr / Mrs/ Miss",
        StudentName: "Kumar Biplab",
        Duration: "2 months",
        Course: "MERN Stack",
        Date: "10th June 2024",
      },
    ],
    fileName: "ASDC_Certificate.xlsx",
  },

  college: {
    fields: [
      {
        key: "CollegeImage",
        label: "College Image",
        name: "CollegeImage",
        fieldType: "ImageUpload",
        accept: "image/*",
      },
      {
        key: "Signature1",
        label: "First Signature",
        name: "Signature1",
        fieldType: "ImageUpload",
        accept: "image/*",
      },
      {
        key: "Signature2",
        label: "Second Signature",
        name: "Signature2",
        fieldType: "ImageUpload",
        accept: "image/*",
      },
      {
        key: "xlsx",
        label: "Add xlsx sheet here",
        name: "ExcelSheet",
        fieldType: "FileUpload",
        accept: ".xlsx, .xls, .numbers",
      },
    ],
    xlsxdata: [
      {
        recipientEmail: "kbs.li2n@gmail.com",
        RegNo: "SSA-2406897657",
        CertificateNo: "SSA-01-2406897657",
        Titels: "Mr / Mrs/ Miss",
        StudentName: "Kumar Biplab",
        Course: "MERN Stack",
        CollegeName: "RNJC College",
        StartDate: "11th June 2024",
        EndDate: "27th June 2024",
        Duration: "16 days",
        Mng_Designation1: "Program Manager",
        Mng_Desg_Add1: "Skyy Skill Academy",
        Mng_Designation2: "Dr B Sreenivasa Reddy",
        Mng_Desg_Add2: "Principal GPREC",
      },
    ],
    fileName: "College_Certificate.xlsx",
  },

  paid: {
    fields: [
      {
        key: "xlsx",
        label: "Add xlsx sheet here",
        name: "ExcelSheet",
        fieldType: "FileUpload",
        accept: ".xlsx, .xls, .numbers",
      },
    ],
    xlsxdata: [
      {
        recipientEmail: "kbs.li2n@gmail.com",
        CertificateNo: "SSA-01-2406897657",
        Titels: "Mr / Mrs/ Miss",
        StudentName: "Kumar Biplab",
        Duration: "2 months",
        Course: "MERN Stack",
        Date: "10th June 2024",
      },
    ],
    fileName: "Paid_Course_Certificate.xlsx",
  },

  shortterm: {
    fields: [
      {
        key: "xlsx",
        label: "Add xlsx sheet here",
        name: "ExcelSheet",
        fieldType: "FileUpload",
        accept: ".xlsx, .xls, .numbers",
      },
    ],
    xlsxdata: [
      {
        recipientEmail: "kbs.li2n@gmail.com",
        CertificateNo: "SSA-01-2406897657",
        Titels: "Mr / Mrs/ Miss",
        StudentName: "Kumar Biplab",
        Course: "MERN Stack",
        StartDate: "11th June 2024",
        EndDate: "27th June 2024",
        Duration: "16 days",
      },
    ],
    fileName: "Short_Term_Certificate.xlsx",
  },

  pgp: {
    fields: [
      {
        key: "xlsx",
        label: "Add xlsx sheet here",
        name: "ExcelSheet",
        fieldType: "FileUpload",
        accept: ".xlsx, .xls, .numbers",
      },
    ],
    xlsxdata: [
      {
        recipientEmail: "kbs.li2n@gmail.com",
        RegNo: "SSA-2406897657",
        CertificateNo: "SSA-01-2406897657",
        Titels: "Mr / Mrs/ Miss",
        StudentName: "Kumar Biplab",
        CourseType: "Master Certification",
        Course: "MERN Stack",
        Duration: "16 days",
        Date: "27th June 2024",
      },
    ],
    fileName: "PGP_Certificate.xlsx",
  },

  lor: {
    fields: [
      {
        key: "Signature1",
        label: "First Signature",
        name: "Signature1",
        fieldType: "ImageUpload",
        accept: "image/*",
      },
      {
        key: "xlsx",
        label: "Add xlsx sheet here",
        name: "ExcelSheet",
        fieldType: "FileUpload",
        accept: ".xlsx, .xls, .numbers",
      },
    ],
    xlsxdata: [
      {
        recipientEmail: "kbs.li2n@gmail.com",
        CertificateNo: "SSA-01-2406897657",
        Date: "27th June 2024",
        Titels: "Mr / Mrs/ Miss",
        StudentName: "Kumar Biplab",
        Course: "MERN Stack",
      },
    ],
    fileName: "Letter_of_Recommendation.xlsx",
  },

  internship: {
    fields: [
      {
        key: "Signature1",
        label: "First Signature",
        name: "Signature1",
        fieldType: "ImageUpload",
        accept: "image/*",
      },
      {
        key: "xlsx",
        label: "Add xlsx sheet here",
        name: "ExcelSheet",
        fieldType: "FileUpload",
        accept: ".xlsx, .xls, .numbers",
      },
    ],
    xlsxdata: [
      {
        recipientEmail: "kbs.li2n@gmail.com",
        Date: "27th June 2024",
        Titels: "Mr / Mrs/ Miss",
        StudentName: "Kumar Biplab",
        CollegeName: "RNJC College",
        Course: "MERN Stack",
        Duration: "16 days",
      },
    ],
    fileName: "Internship_Certificate.xlsx",
  },

  bonafied: {
    fields: [
      {
        key: "xlsx",
        label: "Add xlsx sheet here",
        name: "ExcelSheet",
        fieldType: "FileUpload",
        accept: ".xlsx, .xls, .numbers",
      },
      {
        key: "Signature1",
        label: "First Signature",
        name: "Signature1",
        fieldType: "ImageUpload",
        accept: "image/*",
      },
    ],
    xlsxdata: [
      {
        recipientEmail: "kbs.li2n@gmail.com",
        CertificateNo: "SSA-01-2406897657",
        Date: "27th June 2024",
        Duration: "16 days",
        Titels: "Mr / Mrs/ Miss",
        StudentName: "Kumar Biplab",
        CollegeName: "RNJC College",
        Course: "MERN Stack",
        CoursePrice: "109990",
      },
    ],
    fileName: "Bonafied_Certificate.xlsx",
  },

  clearance: {
    fields: [
      {
        key: "xlsx",
        label: "Add xlsx sheet here",
        name: "ExcelSheet",
        fieldType: "FileUpload",
        accept: ".xlsx, .xls, .numbers",
      },
    ],
    xlsxdata: [
      {
        recipientEmail: "kbs.li2n@gmail.com",
        Titels: "Mr / Mrs/ Miss",
        StudentName: "Kumar Biplab",
        Course: "MERN Stack",
        CourseType: "Online",
        CoursePrice: "10,400",
        Collected_Amount: "10,000",
        Outstanding_dues: "400",
      },
    ],
    fileName: "Clearance_Certificate.xlsx",
  },

  facultyone: {
    fields: [
      {
        key: "CollegeImage",
        label: "College Image",
        name: "CollegeImage",
        fieldType: "ImageUpload",
        accept: "image/*",
      },
      {
        key: "Signature1",
        label: "First Signature",
        name: "Signature1",
        fieldType: "ImageUpload",
        accept: "image/*",
      },
      {
        key: "Signature2",
        label: "Second Signature",
        name: "Signature2",
        fieldType: "ImageUpload",
        accept: "image/*",
      },
      {
        key: "xlsx",
        label: "Add xlsx sheet here",
        name: "ExcelSheet",
        fieldType: "FileUpload",
        accept: ".xlsx, .xls, .numbers",
      },
    ],
    xlsxdata: [
      {
        recipientEmail: "kbs.li2n@gmail.com",
        CertificateNo: "SSA-01-2406897657",
        Titels: "Mr / Mrs/ Miss",
        Student_Designation: "Associate Professor of ECE",
        StudentName: "Kumar Biplab",
        CollegeName: "RNJC College",
        Course: "MERN Stack",
        StartDate: "10th June 2024",
        EndDate: "14th June 2024",
        Mng_Designation1: "Program Manager",
        Mng_Desg_Add1: "Skyy Skill Academy",
        Mng_Designation2: "Dr B Sreenivasa Reddy",
        Mng_Desg_Add2: "Principal GPREC",
      },
    ],
    fileName: "Clearance_Certificate.xlsx",
  },

  facultytwo: {
    fields: [
      {
        key: "CollegeImage",
        label: "College Image",
        name: "CollegeImage",
        fieldType: "ImageUpload",
        accept: "image/*",
      },
      {
        key: "Signature1",
        label: "First Signature",
        name: "Signature1",
        fieldType: "ImageUpload",
        accept: "image/*",
      },
      {
        key: "Signature2",
        label: "Second Signature",
        name: "Signature2",
        fieldType: "ImageUpload",
        accept: "image/*",
      },
      {
        key: "Signature3",
        label: "Third Signature",
        name: "Signature3",
        fieldType: "ImageUpload",
        accept: "image/*",
      },
      {
        key: "Signature4",
        label: "Fourth Signature",
        name: "Signature4",
        fieldType: "ImageUpload",
        accept: "image/*",
      },
      {
        key: "xlsx",
        label: "Add xlsx sheet here",
        name: "ExcelSheet",
        fieldType: "FileUpload",
        accept: ".xlsx, .xls, .numbers",
      },
    ],
    xlsxdata: [
      {
        recipientEmail: "kbs.li2n@gmail.com",
        CertificateNo: "SSA-01-2406897657",
        Titels: "Mr / Mrs/ Miss",
        Student_Designation: "Associate Professor of ECE",
        StudentName: "Kumar Biplab",
        CollegeName: "RNJC College",
        Course: "MERN Stack",
        Duration: "2 days",
        StartDate: "10th June 2024",
        EndDate: "14th June 2024",
        Mng_Designation1: "Program Manager",
        Mng_Desg_Add1: "Skyy Skill Academy",
        Mng_Designation2: "Dr B Sreenivasa Reddy",
        Mng_Desg_Add2: "Principal GPREC",
        Mng_Designation3: "Dr. S Nagaraja Rao Professor & HOD",
        Mng_Desg_Add3: "ECE GPREC",
        Mng_Designation4: "Dr B Sreenivasa Reddy",
        Mng_Desg_Add4: "Principal GPREC",
      },
    ],
    fileName: "Clearance_Certificate.xlsx",
  },
};
